project:
  type: book
  output-dir: .
engine: knitr
book:
  title: "Theory of Statistical Inference"
  output-file: mathstat-LLI
  author:
  - name: "Longhai Li"
    affiliation: "University of Saskatchewan"
    url: "https://longhaisk.github.io/"
  date: last-modified
  chapters:
    - index.qmd
    - introstatinf.qmd
    - sufficiency.qmd
    - loglike.qmd
    - mle.qmd
    - hypothesis.qmd 
    - likelihood-test.qmd
    - umvue.qmd
    - decision.qmd
    - bayesian.qmd    
    - appendix.qmd
metadata-files:
  - resources/bookstyles.yml
