project:
  type: book
  output-dir: .
engine: knitr
execute:
  dir: file
  warning: false
  message: false
  fig-width: 6
  fig-height: 6
  cache: true
  freeze: true
from: markdown+tex_math_single_backslash+tex_math_dollars
filters:
  - shinylive
book:
  title: "Theory of Statistical Inference"
  output-file: mathstat-LLI
  author:
  - name: "Longhai Li"
    affiliation: "University of Saskatchewan"
    url: "https://longhaisk.github.io/"
  date: last-modified
  chapters:
    - index.qmd
    - introstatinf.qmd
    - sufficiency.qmd
    - loglike.qmd
    - mle.qmd
    - hypothesis.qmd 
    - likelihood-test.qmd
    - umvue.qmd
    - decision.qmd
    - bayesian.qmd    
    - appendix.qmd
format:
  custombook-html: default
  custombook-pdf: default
